packages:
  - apps/*
  - packages/*

injectWorkspacePackages: true

allowBuilds:
  '@swc/core': true
  core-js: false
  esbuild: true
  msgpackr-extract: true

minimumReleaseAgeExclude:
  - ultracite@7.10.2

onlyBuiltDependencies:
  - oxlint
