// This file is auto-generated by Modern.js. Do not edit manually.

import {
  createMemoryHistory,
  createRootRouteWithContext,
  createRoute,
  createRouter,
  createRouteStaticData,
  type ModernRouterContext,
  modernLoaderToTanstack,
  modernTanstackRouterFastDefaults,
} from '@modern-js/plugin-tanstack/runtime';

import loader_0 from "../../routes/layout.loader";
import component_0 from "../../routes/page";
import component_1 from "../../routes/reviews/[scanId]/page";
import component_2 from "../../routes/reviews/new/page";
import component_3 from "../../routes/layout";

export const rootRoute = createRootRouteWithContext<ModernRouterContext>()({
  component: component_3,
  loader: modernLoaderToTanstack({ hasSplat: false }, loader_0),
  staticData: createRouteStaticData({
    modernRouteId: "layout",
    modernRouteLoader: loader_0,
  }),
});

const route_page = createRoute({
  getParentRoute: () => rootRoute,
  component: component_0,
  path: "/",
  staticData: createRouteStaticData({
    modernRouteId: "page",
  }),
});

const route_reviews__scanId__page = createRoute({
  getParentRoute: () => rootRoute,
  component: component_1,
  path: "reviews/$scanId",
  staticData: createRouteStaticData({
    modernRouteId: "reviews/(scanId)/page",
  }),
});

const route_reviews_new_page = createRoute({
  getParentRoute: () => rootRoute,
  component: component_2,
  path: "reviews/new",
  staticData: createRouteStaticData({
    modernRouteId: "reviews/new/page",
  }),
});

export const routeTree = rootRoute.addChildren([route_page, route_reviews__scanId__page, route_reviews_new_page]);

export const router = createRouter({
  ...modernTanstackRouterFastDefaults,
  routeTree,
  history: createMemoryHistory({
    initialEntries: ['/'],
  }),
  context: {} as ModernRouterContext,
});
